package id;

public enum MUSIC_ID {
	INTRO_MUSIC
	,GAME_CLEAR_MUSIC
	,GAME_OVER_MUSIC
	,BUTTON_ENTERED_MUSIC
	,BUTTON_PRESSED_MUSIC
	,JOAKIM_KARUD_MIGHTY_LOVE
	,MIGHTY_LOVE_SELECTED
	,JOAKIM_KARUD_WILD_FLOWER
	,WILD_FLOWER_SELECTED
	,BENSOUND_ENERGY
	,ENERGY_SELECTED
	,DRUM_SMALL_1
	,DRUM_SMALL_2
	,DRUM_SMALL_3
	,DRUM_BIG_1
	,DRUM_BIG_2
	,DRUM_BIG_3
}
