CREATE TABLE ACCOUNT (
    ID      VARCHAR2(20) PRIMARY KEY
    ,PW     VARCHAR2(20)
);

CREATE TABLE SCORE (
	ID			VARCHAR2(20)
	,SONG_TITLE VARCHAR2(50)
	,SCORE		NUMBER
	,CONSTRAINT ACCOUT_ID_FK FOREIGN KEY( ID ) REFERENCES ACCOUNT( ID )
);

SELECT  *
FROM    ACCOUNT;

SELECT  *
FROM    SCORE;   

DROP TABLE ACCOUNT;
DROP TABLE SCORE;

COMMIT;
ROLLBACK;